<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__buildingId</name>
   <tag></tag>
   <elementGuidId>91dc2889-90e5-49f7-9e7b-b67e158d734c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buildingId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buildingId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36a34df4-3f6b-45e5-815d-6e0b8f3cb123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buildingId</value>
      <webElementGuid>c1d8e7d9-672e-4be1-9d89-67f04d6c27d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81942b9b-7239-4411-878a-f8ab4de603ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input form-control css-52rcru</value>
      <webElementGuid>897ba960-6805-43e2-857f-7dd554222a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Building ID</value>
      <webElementGuid>2f525eef-d772-4949-a0a6-b5e7c5684a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>15f4df3e-2d39-4e3d-ac80-7cfe17c9300b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildingId</value>
      <webElementGuid>a97be853-7ce8-4191-ba63-1a14485eeaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buildingId&quot;)</value>
      <webElementGuid>4b983854-1c4f-4092-b7ab-fa5e59ed94bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buildingId']</value>
      <webElementGuid>71dc12ba-18d8-4591-b92f-a723dda3d56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-21']/form/div/input</value>
      <webElementGuid>a6d1ffd1-0c9e-4856-b110-13a25373fd32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>abeffe34-6a62-40e7-9aa6-ccba6a67dca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'buildingId' and @type = 'text' and @placeholder = 'Input Building ID' and @id = 'buildingId']</value>
      <webElementGuid>25f3e99d-877b-4e0f-9055-be933e0f5c1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
