<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__buildingName</name>
   <tag></tag>
   <elementGuidId>4c7ddf98-6c6a-435f-8421-23d84edc5e33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buildingName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buildingName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb1abd13-d5b2-4e06-be8b-197e254d80b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buildingName</value>
      <webElementGuid>7040b3e2-0e7e-4e26-a634-1ec12c99aed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ae7345a-20a4-4d79-8081-984a385ea57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input form-control css-52rcru</value>
      <webElementGuid>78c0e3d7-0c75-408b-a4d3-cd290a5301f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Building Name</value>
      <webElementGuid>692dc5a2-3c0d-43e3-9ffc-8a2bcf1a8979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>a5e96697-eba3-4b99-9c7d-831258359314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildingName</value>
      <webElementGuid>7d1b0f46-aa31-4876-929c-c9c536998220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buildingName&quot;)</value>
      <webElementGuid>2ca3422e-aa2d-44f3-9cb9-844e5cc0ec08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buildingName']</value>
      <webElementGuid>dec4e9b8-e07b-4998-9bf3-1323cb057b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-21']/form/div[2]/input</value>
      <webElementGuid>da1b2d7c-48f5-47b0-b471-acdc9b8a8064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4b7faf81-3318-44db-bb71-463c3e4cb105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'buildingName' and @type = 'text' and @placeholder = 'Input Building Name' and @id = 'buildingName']</value>
      <webElementGuid>78c30361-9978-43de-990b-0684d96a16e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
