<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>account_identity</name>
   <tag></tag>
   <elementGuidId>14c811de-9225-4234-9a65-4d7a8185a4fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-button-7</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'menu-button-7' and (text() = 'Angga Juliansyah' or . = 'Angga Juliansyah')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menu-button-7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3728394b-a0f0-435d-8438-20b345623192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-button-7</value>
      <webElementGuid>f640ad76-17f4-4725-99d1-74fb8157728f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ecbbbac-9fd3-4ad8-83d6-4fded8cbf508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>44883d11-9cec-42ab-bc46-9ce9d799ab35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menu-list-7</value>
      <webElementGuid>189f0ba5-32fb-4157-916b-748911fcd8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-menu__menu-button css-kjvu41</value>
      <webElementGuid>e4fdb341-a04b-4bd3-986e-44abca4bff4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Angga Juliansyah</value>
      <webElementGuid>ac849041-ae16-4f9f-9f9c-220f82a7fb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-button-7&quot;)</value>
      <webElementGuid>ae2ba65e-85ac-4152-8190-eac388fc16b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='menu-button-7']</value>
      <webElementGuid>97b99457-161f-4e0c-a022-2f0cda410594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div[2]/ul/li/button</value>
      <webElementGuid>9b46ebd2-a24d-437f-b26c-ad3a1b372a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::button[1]</value>
      <webElementGuid>f1b6349d-85a0-4d1e-b538-68a02ff43543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quality Control'])[1]/following::button[1]</value>
      <webElementGuid>6d34a8b9-1c4e-4393-b756-8eee29d179ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::button[1]</value>
      <webElementGuid>7d3b899d-1485-40b1-963e-f8c93258b404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>e7d1dc7a-72f3-48cf-87d6-7f2427d5a1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@class='header-name']</value>
      <webElementGuid>53442da7-044a-4088-99c0-42c23592617d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
