<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>467b117e-7801-4227-a698-9d42d6b2d42c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.w-100.mt-3.mb-4.style_btn-cm-primary__38lnq.btn-cm-primary.css-taj3dd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c14cddc-d453-4543-97dc-17edeef3cfe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a1ae3ddc-fdc5-4be9-9540-7f0cb1a90309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button w-100 mt-3 mb-4 style_btn-cm-primary__38lnq btn-cm-primary css-taj3dd</value>
      <webElementGuid>271dc328-0d7e-4c16-baa0-627e882b8565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>ddc55626-4f48-4e4d-a03d-f94df75446ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;main-content-wrapper vh-100 mt-0 px-0 py-0 style_login__q5zHS&quot;]/div[1]/form[1]/div[@class=&quot;css-1s2f72d&quot;]/div[@class=&quot;text-center my-auto css-1jlbmqw&quot;]/div[@class=&quot;mx-auto px-4 text-left css-0&quot;]/button[@class=&quot;chakra-button w-100 mt-3 mb-4 style_btn-cm-primary__38lnq btn-cm-primary css-taj3dd&quot;]</value>
      <webElementGuid>23b02b1f-9656-4db3-8946-18c886d1b168</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>beffdee2-4125-4c53-a045-7e0d1a629c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div/button</value>
      <webElementGuid>514ae346-7d1c-48bb-8057-08c532f67fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>37876586-4802-4a37-bf8d-a18efc5ff6e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>8bce5609-edb9-430a-8a62-7cdf647b3a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>8f67d592-104f-44e9-981e-174e04e6a21a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
