<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Are you sure you want to log outCancelLogout</name>
   <tag></tag>
   <elementGuidId>6a8a82f1-93d3-4537-aebe-dcfb56e3e4ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chakra-modal--body-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1512f8b5-dbbd-4dc6-9fa2-d92f37ed5ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-modal__body text-center css-1oveffk</value>
      <webElementGuid>afc4062c-d605-4550-aa2f-bd1764b383f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chakra-modal--body-2</value>
      <webElementGuid>fc2f138e-c796-4a98-bee8-5a3dd18a3bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Are you sure you want to log out?CancelLogout</value>
      <webElementGuid>b96706b3-2f8f-404e-9d1a-da24c65844cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-2&quot;)</value>
      <webElementGuid>fe7c7bce-b0a1-43c1-b831-5ce6f60af579</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-2']</value>
      <webElementGuid>e14b1bc2-09c5-4bb3-8dfb-69253176eb6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-2']/div</value>
      <webElementGuid>286708fb-ea5e-4f8a-a524-274700cdfbe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[8]</value>
      <webElementGuid>d16539dc-97e0-48b5-a5d5-7021169229bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::div[8]</value>
      <webElementGuid>6bc0cf02-c768-456d-8c52-e3f809004c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div</value>
      <webElementGuid>054b11cd-b729-46a8-ac06-1b753923fbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'chakra-modal--body-2' and (text() = 'Are you sure you want to log out?CancelLogout' or . = 'Are you sure you want to log out?CancelLogout')]</value>
      <webElementGuid>a04bfe61-e9e5-4ee9-99df-031b4864ad8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
