<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup_account_is_used</name>
   <tag></tag>
   <elementGuidId>3063fb75-0ea5-48e1-8d0a-8c0af9121afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-2']/container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>2fcee6cf-0ef4-4535-b60c-43df382dfdea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-2&quot;)/container[1]</value>
      <webElementGuid>92ef9db1-092e-4674-b57e-cee23394efe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-2']/container</value>
      <webElementGuid>0388ec29-b8ce-4621-ab9e-3fbb8ca5135a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::container[1]</value>
      <webElementGuid>47d72010-0121-4d82-88f8-bcb0204aec0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::container[1]</value>
      <webElementGuid>f0c39a23-b227-45bb-80e3-1211fe43e224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::container[5]</value>
      <webElementGuid>a53c49d4-d7b2-460f-9a03-8683c3cefc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::container[5]</value>
      <webElementGuid>34b44a2f-4ed7-4886-abdb-7141e9ddf801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//container</value>
      <webElementGuid>07003283-3cb3-422d-9755-719f6598969a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
