<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_Approval Confirmation</name>
   <tag></tag>
   <elementGuidId>0999c950-ce0c-4e8b-805a-c1a4ccc34c03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chakra-modal--header-review-confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='chakra-modal--header-review-confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>bf51df57-d64d-4123-a11d-c891984ec8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-modal__header css-9fgtzh</value>
      <webElementGuid>06aa68aa-148c-4160-b007-3792682038f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chakra-modal--header-review-confirm</value>
      <webElementGuid>cbd3b241-48e8-4406-b4ba-ce4f450e5a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approval Confirmation</value>
      <webElementGuid>1f3f9f82-ac02-46a7-afbc-bb878194333c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--header-review-confirm&quot;)</value>
      <webElementGuid>c0f98cef-5c30-4182-b8c2-cfb1690d4451</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//header[@id='chakra-modal--header-review-confirm']</value>
      <webElementGuid>578ce547-69f2-4ad8-ae88-7efd26c2a05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-review-confirm']/header</value>
      <webElementGuid>a1a679a5-1fe3-4d71-b359-59c976b29778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[2]/following::header[1]</value>
      <webElementGuid>cd1051dc-1e54-49f7-b522-d748f4e95b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[2]/following::header[1]</value>
      <webElementGuid>d20f0444-dba0-4c96-bffe-8c883e40dce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::header[1]</value>
      <webElementGuid>e2315ce6-5d5c-4861-a6b4-8aecbc3fcb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Approval']/parent::*</value>
      <webElementGuid>7da305c4-8ca8-4dee-bde5-1257f6025edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[4]/div/section/header</value>
      <webElementGuid>a0631f73-136c-4fed-a6a0-954d68f659c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[@id = 'chakra-modal--header-review-confirm' and (text() = 'Approval Confirmation' or . = 'Approval Confirmation')]</value>
      <webElementGuid>f16fc95c-e7d2-4f93-a005-5da23a518df9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
