<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pin-input-37-1</name>
   <tag></tag>
   <elementGuidId>ada8f1d0-8ec9-4ed3-a49d-c0ce849913e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pin-input-37-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pin-input-37-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3348f8b6-8ec7-4ce9-97ee-a88305e43e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Please enter your pin code</value>
      <webElementGuid>5a92a505-45d2-4fda-9c32-68b54ece691d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>669ddead-12b0-4f0a-9c3b-22deb8d8860d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f7465d90-872a-4203-bf2a-397fa1197052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pin-input-37-1</value>
      <webElementGuid>a4f2348f-1259-48e6-ba27-ec79fb30edd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>722a0c30-ae02-41ed-93f4-8446a8fd9d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-pin-input css-17u1q9k focus-visible</value>
      <webElementGuid>e42c8433-f99a-4418-967f-2ccc5a186601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>80709145-8ec8-46d8-b6a8-2bee6b504d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pin-input-37-1&quot;)</value>
      <webElementGuid>87625e3f-4446-457c-8644-b089db2a0e18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pin-input-37-1']</value>
      <webElementGuid>c6575f13-d369-4f81-b195-56cbcb89f289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-review-confirm']/form/div/div/input[2]</value>
      <webElementGuid>616a5e9c-99d5-4aa9-af38-1c306c297481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>a89a437a-fc7c-4ce8-a7eb-7bfc4f1013f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'pin-input-37-1']</value>
      <webElementGuid>acf934ac-2012-4498-9999-8b744afa2f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
