<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>c999bb8a-2cb7-444f-8f8e-ca9e42481ee6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.w-100.mt-3.mb-4.style_btn-cm-primary__38lnq.btn-cm-primary.css-taj3dd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a7b3f0ea-e19c-4340-8239-b9850c39d690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>340cd9d7-3414-47f9-8d4a-094b579ea2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button w-100 mt-3 mb-4 style_btn-cm-primary__38lnq btn-cm-primary css-taj3dd</value>
      <webElementGuid>8401c0bb-9335-4421-a4c3-dc6c144a5fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>f356b45c-9aca-4010-a4b8-a847d774c4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;main-content-wrapper vh-100 mt-0 px-0 py-0 style_login__q5zHS&quot;]/div[@class=&quot;style_form-container__1OCHe&quot;]/form[1]/div[@class=&quot;css-1s2f72d&quot;]/div[@class=&quot;text-center my-auto undefined css-metzo1&quot;]/div[@class=&quot;mx-auto px-4 text-left css-0&quot;]/button[@class=&quot;chakra-button w-100 mt-3 mb-4 style_btn-cm-primary__38lnq btn-cm-primary css-taj3dd&quot;]</value>
      <webElementGuid>f1805585-ef97-45b3-8584-f5da7942130c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>8133b1a8-c2a5-4b5a-96ab-edbf29539751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div/button</value>
      <webElementGuid>5f1cb95b-db03-4cac-b272-d97995c31362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>e5cfb2e4-9ab9-46c2-add8-43f83a1cce82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9a9c326e-0f05-4686-a249-9a21e841a2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>f7332223-f5b0-45b1-abfb-ad6416790325</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
