<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Contact Agar 2</name>
   <tag></tag>
   <elementGuidId>46da3c24-73f7-4ad6-9ec9-4fa0b7b1c29c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-14-option-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-14-option-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb1865c1-ea08-4931-b283-3f3b3350537a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1bhb5c-option</value>
      <webElementGuid>74fd2e66-99f5-493f-bce1-021d6041a51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5847e92c-abbb-4b6f-9cea-e588da2154fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-14-option-3</value>
      <webElementGuid>8d746276-0d88-429b-ba68-294dd1be41eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>331b9d53-738b-4722-b492-4630f4be8432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact Agar 2</value>
      <webElementGuid>1d559a91-c7b3-45da-b537-cd6a8fc978ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-14-option-3&quot;)</value>
      <webElementGuid>ddce0f36-fdd7-4f3e-81ea-c2e10397f3a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-14-option-3']</value>
      <webElementGuid>fe8211a4-bf16-4ac2-9028-c7b4762548bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-14-listbox']/div/div[4]</value>
      <webElementGuid>11a63d44-59a5-4807-83b0-40f1034d2a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Triptic Soy Agar'])[1]/following::div[1]</value>
      <webElementGuid>0da9338e-94c5-4766-b0c3-9a563bbd5cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item 0004'])[1]/following::div[2]</value>
      <webElementGuid>59f33520-21a1-42fd-b75d-bdbc1da31d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test media ada'])[1]/preceding::div[1]</value>
      <webElementGuid>f33596e7-a37a-4598-9a2c-0b6ca9c8754d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test media ada'])[2]/preceding::div[2]</value>
      <webElementGuid>e60d08b6-ada3-4307-9ec5-22ac8f7a540e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contact Agar 2']/parent::*</value>
      <webElementGuid>8125c32f-fd26-4836-87ee-503b84e4cce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[4]</value>
      <webElementGuid>311d0289-627b-433b-b3e1-7f391e24800e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-14-option-3' and (text() = 'Contact Agar 2' or . = 'Contact Agar 2')]</value>
      <webElementGuid>ae15960d-3d8e-4286-b88e-ed9f53c78ee5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
