<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__chakra-input disabled-input css-ygxf8c</name>
   <tag></tag>
   <elementGuidId>5a05411c-5070-421f-8f3f-bff10d09526e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.chakra-input.disabled-input.css-ygxf8c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1882d3a-3d12-41e7-b0c4-894c2a961d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Tanggal Mulai Sampling</value>
      <webElementGuid>8407f63d-ad3b-4718-bf31-a362c36c1257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input disabled-input css-ygxf8c</value>
      <webElementGuid>5719b727-1444-4317-ba0e-91263584bfad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>239becaa-4d80-430a-be0a-bd2976c99ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popover-trigger-65&quot;)/div[@class=&quot;chakra-input__group css-4302v8&quot;]/input[@class=&quot;chakra-input disabled-input css-ygxf8c&quot;]</value>
      <webElementGuid>cd16d3fb-b2aa-482b-b5ed-d3cd4c6e0997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>6ef8fb4b-640d-4a0d-80f0-7cf949f26e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popover-trigger-65']/div/input</value>
      <webElementGuid>159f890a-433c-481d-af32-a01772caeea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>af201eb3-5165-4036-aaf6-d49c7885f6e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Pilih Tanggal Mulai Sampling']</value>
      <webElementGuid>287e7d5b-cb26-4c95-b5d9-07b0a6d20f0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
