<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>89a0940b-6738-4ddb-956c-377a11e2b564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.w-100.mt-3.mb-4.style_btn-cm-primary__38lnq.btn-cm-primary.css-taj3dd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88a5b41d-9081-4adc-a5a9-d2b56786efc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a3fa2f6d-d2c4-42b0-bacf-959d1cae2e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button w-100 mt-3 mb-4 style_btn-cm-primary__38lnq btn-cm-primary css-taj3dd</value>
      <webElementGuid>17b31aa3-e363-4560-8c22-de348421d255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>b7eaa1fb-fe83-46f2-84fc-e8f1f8b0c01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;main-content-wrapper vh-100 mt-0 px-0 py-0 style_login__q5zHS&quot;]/div[@class=&quot;style_form-container__1OCHe&quot;]/form[1]/div[@class=&quot;css-1s2f72d&quot;]/div[@class=&quot;text-center my-auto undefined css-metzo1&quot;]/div[@class=&quot;mx-auto px-4 text-left css-0&quot;]/button[@class=&quot;chakra-button w-100 mt-3 mb-4 style_btn-cm-primary__38lnq btn-cm-primary css-taj3dd&quot;]</value>
      <webElementGuid>4e522ac4-8626-44da-8020-790279b0e905</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>29c17531-af5b-46ee-86aa-21a71b9f5915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div/button</value>
      <webElementGuid>86265b4e-08a8-4ce5-a91e-e80f1bfb7ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>1826aa4a-b6b8-4136-8d6b-0d91f543a6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7db8a4a7-8641-4e95-8968-2eddbc712b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>e60874a9-95c2-4bdf-b2e5-480eadb795c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
