<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit_Req</name>
   <tag></tag>
   <elementGuidId>0f00bb4f-9f0a-4f96-87d7-b15ffcff9bcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-10jc89h</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class='chakra-button css-10jc89h']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9a38689-f07a-4e6c-a079-e6c64c05041e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2be30a6-264d-404f-935a-bbfe471d036f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-10jc89h</value>
      <webElementGuid>6d8601f8-f531-4d80-a0fa-726645913f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save &amp; Submit</value>
      <webElementGuid>49e6e4c9-aab1-4cd9-8b42-5cd0539ee4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal-34&quot;)/footer[@class=&quot;chakra-modal__footer css-v7opq8&quot;]/button[@class=&quot;chakra-button css-10jc89h&quot;]</value>
      <webElementGuid>dbd57c91-7966-4a44-82a2-c9a354186509</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>071f6309-c743-483b-a899-1afd42e347b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-34']/footer/button[3]</value>
      <webElementGuid>9d3c9e2a-1a2a-4729-be53-dfe57b0ca19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save as Draft'])[1]/following::button[1]</value>
      <webElementGuid>4bb1f3f4-4c88-4547-b03c-f50803451fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::button[2]</value>
      <webElementGuid>419604eb-54a0-49d7-9914-d1e6782de0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save &amp; Submit']/parent::*</value>
      <webElementGuid>72686a10-a73e-4429-91bb-0c25495030c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>291e3575-c459-4ea5-8724-2b4964486e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@class='chakra-button css-10jc89h']</value>
      <webElementGuid>0bcf1f2b-48c0-45cc-950e-32e4ddfa58a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
