<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GD-15-L1  Fasilitas Pemurnian Toksoid</name>
   <tag></tag>
   <elementGuidId>cf0406ab-ae9b-42cf-855b-d2cb4e181f18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-8-option-91</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-8-option-91']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b8fff102-d2d9-4b0f-8405-393a80446c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-1bhb5c-option</value>
      <webElementGuid>3812345a-cd87-4090-85ea-8051c0e12450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5c012a46-942b-4251-9d23-56bc7fa92182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-8-option-91</value>
      <webElementGuid>6d3915ef-15fc-41e0-b2aa-1a69c49cce41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>35a31a4a-9da4-4926-bd62-eab1188ceb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GD-15-L1 | Fasilitas Pemurnian Toksoid</value>
      <webElementGuid>3b309cbf-9b7d-4d26-942f-fa1ed303bfbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-8-option-91&quot;)</value>
      <webElementGuid>4a5ca2b3-deed-4430-b36b-ef18738c1255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-8-option-91']</value>
      <webElementGuid>6abc71ee-6a74-488f-b2bd-d0e733fd0934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-8-listbox']/div/div[4]</value>
      <webElementGuid>d5e62e1a-6e6b-4552-af77-2825fb435e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GD-11-L1 | Fasilitas Produksi Bulk Virus Multiproduk'])[1]/following::div[1]</value>
      <webElementGuid>992f9ffe-f133-40ce-b6d1-c37b14dbe399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GD-36-L1 | Fasilitas Produksi Bulk Virus Multiproduk'])[1]/following::div[2]</value>
      <webElementGuid>f6d9b5ce-d58d-4282-b593-d0dc65020a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GD-15-L1 | Fasilitas Pemurnian Toksoid']/parent::*</value>
      <webElementGuid>dca3f050-1c86-472b-a27b-636827aeffea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[4]</value>
      <webElementGuid>ac2982b5-e650-4fac-ad2a-7f47bdc9ca50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-8-option-91' and (text() = 'GD-15-L1 | Fasilitas Pemurnian Toksoid' or . = 'GD-15-L1 | Fasilitas Pemurnian Toksoid')]</value>
      <webElementGuid>d5428dff-37f5-4ad4-82a1-eaf04656699e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
