<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Batch_noBatch</name>
   <tag></tag>
   <elementGuidId>7d4658d5-82e2-47b4-9638-227371ecd934</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noBatch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noBatch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d34b997-cf97-4c58-b7c7-db88b972ae64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>noBatch</value>
      <webElementGuid>bfb533a0-412b-4a1c-9973-a348216d3b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input border-color-gray css-hl8i8l focus-visible</value>
      <webElementGuid>0d19869a-63f9-4e19-8fa3-0780903a2227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nomor Batch</value>
      <webElementGuid>c3abc62b-86f5-49cb-8962-52ed3c2bf838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb380e46-09a5-4e7b-87dc-58e256b8e309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>cf80a860-0ecd-4d16-a430-4b87c1805926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>language</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>c72066de-a10b-46a4-bf3a-df383b6b1d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>i18n</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>dea6566b-c871-4474-9dc5-55679e9904de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noBatch</value>
      <webElementGuid>350aa4a6-da2d-4910-9366-d4f7abecdaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noBatch&quot;)</value>
      <webElementGuid>c0eded7d-3d36-4246-8e95-bfc689b9af91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noBatch']</value>
      <webElementGuid>6ab316e0-a5f8-430d-8bb0-7f846e1f4fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div/div[2]/div/div[6]/div/div/div/input</value>
      <webElementGuid>49ff4f20-c785-48c0-b44e-e19aeedea3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>a54e00d5-f957-4e7f-bdc1-945928dc863a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'noBatch' and @placeholder = 'Masukkan Nomor Batch' and @type = 'text' and @id = 'noBatch']</value>
      <webElementGuid>d8e6108b-0dba-43aa-b7e3-2d645621bebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
